<a href="https://colab.research.google.com/github/Salome0119/Arreglos_12_08_2025/blob/main/Vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Los vectores son reservas de memoria para almacenar informacion, solo puede ser de un tipo, si es numerico, es numerico, si es texto, debe continuar siendo texto, est aplica para las matrices.
Los arreglos son identificadores son estaticos, esto significa que es otra forma de definir variables y constantes

In [1]:
import numpy as np # np es un aleas para recortar el nombre de numpy

vector = np.array([1, 2, 3, 4, 5])#Creamos un vector de numpy
print(vector) #Imprimimos el vector
#Quiero imprimir el tercer elemento del vector
print(vector[2])

"""
 Los vectores no son como las listas, no tienen un método append()
 para agregar elementos y no tienen un método pop() para eliminar elementos,
 pero sí tienen método reshape() para cambiar su forma, adicionalmente despues
 de creado no se puede cambiar el tamaño del vector

"""

vector1 = np.zeros(5)# Imprimimos el vector de ceros
print(vector1)
vector2 = np.ones(5)# Imprimimos el vector de unos
print(vector2)
vector3 = np.arange(1,10)# Imprimimos el vector de rango del 1 al 10
print("rango",vector3)
vector4 = np.linspace(1, 10, 5) #Creamo un vector de 5 números entre 1 y 10
print("linspace",vector4)
vector5 = np.random.rand(10)#Numeros aleatorias del 0 a 100
print(vector5)
vector6 = np.random.randint(1, 10, 10)
print(vector6)

[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango [1 2 3 4 5 6 7 8 9]
linspace [ 1.    3.25  5.5   7.75 10.  ]
[0.51630211 0.32222437 0.73011293 0.24978937 0.89611849 0.53431818
 0.98838506 0.94777747 0.06658215 0.86939959]
[1 9 8 3 5 3 5 5 5 2]


In [2]:
import numpy as np
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
#Suma de vectores
suma = vector1 + vector2
print("Suma de vectores ", suma) #Imprimir suma

#Multiplicación de vectores
producto = vector1 * vector2 #Multiplicación de vectores
print("Producto de vectores ", producto) #Imprimir multiplicación

#División de vectores
division = vector1 / vector2 #División de vectores
print("División de vectores ", division) #Imprimir división

#Resta de vectores
resta = vector1 - vector2 #Resta de vectores
print("Resta de vectores ", resta) #Imprimir resta

#Potencia de vectores
potencia = vector1 ** 2 #Potencia de vectores
print("\"Potencia de vectores ", potencia) #Imprimir potencia


Suma de vectores  [5 7 9]
Producto de vectores  [ 4 10 18]
División de vectores  [0.25 0.4  0.5 ]
Resta de vectores  [-3 -3 -3]
"Potencia de vectores  [1 4 9]


Colores

In [3]:
import numpy as np
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
#Suma de vectores
suma = vector1 + vector2
print("\033[96mSuma de vectores\033[0m ", suma) #Imprimir suma

#Multiplicación de vectores
producto = vector1 * vector2 #Multiplicación de vectores
print("\033[92mProducto de vectores\033[0m ", producto) #Imprimir multiplicación

#División de vectores
division = vector1 / vector2 #División de vectores
print("\033[95mDivisión de vectores\033[0m ", division) #Imprimir división

#Resta de vectores
resta = vector1 - vector2 #Resta de vectores
print("\033[93mResta de vectores\033[0m ", resta) #Imprimir resta

#Potencia de vectores
potencia = vector1 ** 2 #Potencia de vectores
print("\033[91mPotencia de vectores\033[0m:", potencia) #Imprimir potencia


Suma de vectores  [5 7 9]
Producto de vectores  [ 4 10 18]
División de vectores  [0.25 0.4  0.5 ]
Resta de vectores  [-3 -3 -3]
Potencia de vectores: [1 4 9]
